# MangoParty Configuration

# Debug mode - set to true to enable debug messages in console
debug: false

# Party Settings
party:
  # Maximum party size
  max-size: 8
  # Invite timeout in seconds
  invite-timeout: 60
  # Auto-disband empty parties
  auto-disband: true

# Match Settings
match:
  # Countdown duration in seconds
  countdown-duration: 5
  # Minimum players required to start a match
  min-players: 2
  # Maximum match duration in minutes (0 = unlimited)
  max-duration: 30
  # Match messages
  messages:
    winner: "&#4ECDC4&l⚡ &#FFD700{winner} &#4ECDC4won the match! &#4ECDC4&l⚡"
    draw: "&#FFD700&l⚖ &#FFE66DThe match ended in a draw! &#FFD700&l⚖"
    time-remaining: "&#A0A0A0Time remaining: &#FF6B6B{time}"
    time-up: "&#FF6B6B&l⏰ &#FF6B6BTime's up! The match has ended. &#FF6B6B&l⏰"

# Arena Settings
arena:
  # Auto-regenerate arenas after matches
  auto-regenerate: true
  # Delay before regeneration in seconds
  regeneration-delay: 5

# Scoreboard Settings
scoreboard:
  title: "&#FFD700&l✦ &#FFA500&lMango&#FFD700&lParty &#FFD700&l✦"
  lines:
    - "&#555555⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯"
    - "&#FF6B6B⚔ &#A0A0A0Arena: &#FFFFFF{arena}"
    - "&#4ECDC4⚒ &#A0A0A0Kit: &#FFFFFF{kit}"
    - "&#45B7D1⚙ &#A0A0A0Mode: &#FFFFFF{match_type}"
    - "&#555555⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯"
    - "&#FFE66D⚡ &#A0A0A0Status: &#FFFFFF{status}"
    - "&#4ECDC4☯ &#A0A0A0Players: &#FFFFFF{players_alive}/{players_total}"
    - "&#555555⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯"
    - "&#FFEAA7✪ &#A0A0A0Stats:"
    - "  &#FF7675☠ &#A0A0A0Kills: &#FFFFFF{kills}"
    - "  &#74B9FF✝ &#A0A0A0Deaths: &#FFFFFF{deaths}"
    - "&#555555⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯"
    - "&#A29BFE⏰ &#A0A0A0Time: &#FFFFFF{time}"
    - "&#555555⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯"
    - "&#FFD93D&lmangoparty.com"

# Messages
messages:
  prefix: "&#FFD700&l[&#FFA500&lMango&#FFD700&lParty&#FFD700&l] &r"
  player-only: "&#FF6B6B&lError: &#FF6B6BThis command can only be used by players!"
  player-not-found: "&#FF6B6B&lError: &#FF6B6BPlayer not found or offline!"
  party-created: "&#4ECDC4&lSuccess! &#4ECDC4Party created successfully!"
  party-disbanded: "&#FF6B6B&lNotice: &#FF6B6BParty has been disbanded!"
  invite-sent: "&#4ECDC4&lInvite: &#4ECDC4Sent to &#FFE66D{player}&#4ECDC4!"
  invite-received: "&#FFE66D{player} &#A0A0A0has invited you to their party! &#FFD700&l[CLICK TO JOIN]"
  player-joined: "&#4ECDC4&l+ &#FFE66D{player} &#A0A0A0joined the party!"
  player-left: "&#FF6B6B&l- &#FFE66D{player} &#A0A0A0left the party!"
  leadership-transferred: "&#FFD700&lLeadership: &#FFE66D{player} &#A0A0A0is now the party leader!"
  match-starting: "&#FFD700&l⚔ &#FFE66DMatch starting in &#FF6B6B&l{seconds} &#FFE66Dseconds! &#FFD700&l⚔"
  match-started: "&#4ECDC4&l▶ &#4ECDC4Match started! Good luck! &#4ECDC4&l◀"
  match-ended: "&#FFD700&l✦ &#FFE66DMatch ended! &#FFD700&l✦"
  
  # Party vs Party Duel Messages
  party-duel:
    challenge-received: "&#FFD700&l⚔ &#FFE66D{challenger_party} &#A0A0A0has challenged your party to a duel! &#FFD700&l⚔"
    kit-info: "&#A0A0A0Kit: &#FFFFFF{kit} &#555555| &#A0A0A0Expires in: &#FF6B6B60 seconds"
    challenge-sent: "&#4ECDC4&lDuel: &#4ECDC4Request sent to &#FFE66D{target_party} &#4ECDC4with kit: &#FFFFFF{kit}"
    challenge-accepted: "&#4ECDC4&lDuel: &#4ECDC4Accepted! Starting match with kit: &#FFFFFF{kit}"
    challenge-declined: "&#FF6B6B&lDuel: &#FFE66D{target_party} &#A0A0A0has declined your duel request."
    challenge-expired: "&#FF6B6B&lExpired: &#FF6B6BYour duel request to &#FFE66D{target_party} &#FF6B6Bhas expired."
    challenge-expired-target: "&#FF6B6B&lExpired: &#FF6B6BThe duel request from &#FFE66D{challenger_party} &#FF6B6Bhas expired."
    no-pending-duel: "&#FF6B6B&lError: &#FF6B6BYou don't have any pending duel requests!"
    duel-not-found: "&#FF6B6B&lError: &#FF6B6BDuel request not found or challenger is offline!"
    already-in-match: "&#FF6B6B&lError: &#FF6B6BOne of the parties is already in a match!"
    no-available-arenas: "&#FF6B6B&lError: &#FF6B6BNo available arenas for the duel!"
    kit-not-found: "&#FF6B6B&lError: &#FF6B6BKit not found!"
  
  # Player Duel Messages
  player-duel:
    challenge-received: "&#FFD700&l⚔ &#FFE66D{challenger} &#A0A0A0has challenged you to a duel! &#FFD700&l⚔"
    kit-info: "&#A0A0A0Kit: &#FFFFFF{kit} &#555555| &#A0A0A0Rounds: &#FFFFFF{rounds} &#555555| &#A0A0A0Expires in: &#FF6B6B60 seconds"
    challenge-sent: "&#4ECDC4&lDuel: &#4ECDC4Request sent to &#FFE66D{target} &#4ECDC4with kit: &#FFFFFF{kit}, first to &#FFFFFF{rounds} &#4ECDC4rounds"
    challenge-accepted: "&#4ECDC4&lDuel: &#4ECDC4Accepted! Starting match with kit: &#FFFFFF{kit}"
    challenge-declined: "&#FF6B6B&lDuel: &#FFE66D{target} &#A0A0A0has declined your duel request."
    challenge-expired: "&#FF6B6B&lExpired: &#FF6B6BYour duel request to &#FFE66D{target} &#FF6B6Bhas expired."
    challenge-expired-target: "&#FF6B6B&lExpired: &#FF6B6BThe duel request from &#FFE66D{challenger} &#FF6B6Bhas expired."
    no-pending-duel: "&#FF6B6B&lError: &#FF6B6BYou don't have any pending duel requests!"
    duel-not-found: "&#FF6B6B&lError: &#FF6B6BDuel request not found or challenger is offline!"
    already-in-match: "&#FF6B6B&lError: &#FF6B6BOne of the players is already in a match!"
    already-has-request: "&#FF6B6B&lError: &#FF6B6B{target} already has a pending duel request!"
    no-available-arenas: "&#FF6B6B&lError: &#FF6B6BNo available arenas for the duel!"
    kit-not-found: "&#FF6B6B&lError: &#FF6B6BKit '{kit}' not found!"
    round-ended: "&#FFD700&lRound {round}: &#FFE66D{player1} &#FFFFFF{score1} &#555555- &#FFFFFF{score2} &#FFE66D{player2}"
    duel-victory: "&#4ECDC4&lVictory! &#FFE66D{winner} &#4ECDC4won the duel against &#FF6B6B{loser} &#555555(&#FFD700{winner_score}&#555555-&#FFD700{loser_score}&#555555)"
    self-duel: "&#FF6B6B&lError: &#FF6B6BYou cannot duel yourself!"
    invalid-rounds: "&#FF6B6B&lError: &#FF6B6BRounds must be between 1 and 10!"
    usage: "&#FF6B6B&lUsage: &#FF6B6B/duel <player> <kit> <rounds>"
    accept-usage: "&#FF6B6B&lUsage: &#FF6B6B/duelaccept <player>"
    decline-usage: "&#FF6B6B&lUsage: &#FF6B6B/dueldecline <player>"
    cannot-damage-other-duel: "&#FF6B6B&lError: &#FF6B6BYou cannot damage players in other duels!"
